Hotel-Umg-Frontend/Models/Detalle.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Hotel_Umg_Frontend.Models
{
    public class Detalle
    {
        public int idDetalle { get; set; }

        public int idReservacion { get; set; }
        public virtual Reservacion Reservacion { get; set; }

        public int idHabitacion { get; set; }
        public virtual Habitacion Habitacion { get; set; }

        public DateTime fechaReserva { get; set; }

    }
}

Hotel-Umg-Frontend/Controllers/DetalleController.cs
using Hotel_Umg_Frontend.Models;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Hotel_Umg_Frontend.Controllers
{

    public class DetalleController : Controller
    {
        public class Respuesta
        {
            public List<detalle> detalles { get; set; }
            public List<Reservacion> reservaciones { get; set; }
            public List<Habitacion> habitaciones { get; set; }

            public Respuesta(List<detalle> detalles, List<Reservacion> reservaciones, List<Habitacion> habitaciones)
            {
                this.detalles = detalles;
                this.reservaciones = reservaciones;
                this.habitaciones = habitaciones;
            }
        }
        private string urlApi = System.Configuration.ConfigurationManager.AppSettings["ApiUrl"];

        // GET: detalle
        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> detalle()
        {
            ViewBag.Message = "detalles";
            List<detalle> detalles = new List<detalle>();
            List<Reservacion> reservaciones = new List<Reservacion>();
            List<Habitacion> habitaciones = new List<Habitacion>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(urlApi);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                try
                {
                    HttpResponseMessage response = await client.GetAsync("/Api/detalle");
                    if (response.IsSuccessStatusCode)
                    {
                        detalles = await response.Content.ReadAsAsync<List<detalle>>();
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, $"Error en la solicitud al API. Código de estado: {response.StatusCode}");
                    }

                    HttpResponseMessage responseReservacion = await client.GetAsync("/Api/reservacion");
                    if (responseReservacion.IsSuccessStatusCode)
                    {
                        reservaciones = await responseReservacion.Content.ReadAsAsync<List<Reservacion>>();
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, $"Error en la solicitud al API. Código de estado: {response.StatusCode}");
                    }
                    HttpResponseMessage responseHabitacion = await client.GetAsync("/Api/habitacion");
                    if (responseHabitacion.IsSuccessStatusCode)
                    {
                        habitaciones = await responseHabitacion.Content.ReadAsAsync<List<Habitacion>>();
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, $"Error en la solicitud al API. Código de estado: {response.StatusCode}");
                    }
                }
                catch (HttpRequestException e)
                {
                    ModelState.AddModelError(string.Empty, $"Error al conectarse al API: {e.Message}");
                }
                catch (Exception e)
                {
                    ModelState.AddModelError(string.Empty, $"Ocurrió un error inesperado: {e.Message}");
                }
            }
            Respuesta respuesta = new Respuesta(detalles, reservaciones, habitaciones);
            return View(respuesta);
        }

        // Crear detalle_reservacion
        [HttpPost]
        public async Task<ActionResult> Crear(detalle nuevoDetalle)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(urlApi);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage response = await client.PostAsJsonAsync("/Api/detalle", nuevoDetalle);
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("detalle");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Error al crear el detalle de la reservacion");
                    return View(nuevoDetalle);
                }
            }
        }

        // Editar detalle_reservacion
        [HttpPost]
        public async Task<ActionResult> Editar(detalle detalleEditado)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(urlApi);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage response = await client.PutAsJsonAsync($"/Api/detalle/{detalleEditado.idDetalle}", detalleEditado);
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("detalle");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Error al editar el detalle de la reservacion");
                    return View(detalleEditado);
                }
            }
        }

        // Eliminar detalle_reservacion
        [HttpPost]
        public async Task<ActionResult> Eliminar(string idDetalle)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(urlApi);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                HttpResponseMessage response = await client.DeleteAsync($"/Api/detalle/{idDetalle}");
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("detalle");
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Error al eliminar el detalle de la reservacion");
                    return RedirectToAction("detalle");
                }
            }
        }
    }
}

Hotel-Umg-Frontend/Views/Detalle/Detalle.cshtml
@model Hotel_Umg_Frontend.Controllers.DetalleController.Respuesta

<div class="container d-flex mb-5">
    <div class="page-header d-flex w-100 justify-content-between">
        <h1>Detalles de la Reservacion</h1>
        <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#crearModal">
            Nuevo Detalle
        </button>
    </div>
</div>

<!-- Crear -->
<div class="modal fade" id="crearModal" tabindex="-1" aria-labelledby="crearModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="crearModalLabel">Crear un nuevo Empleado</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Crear", "Detalle", FormMethod.Post))
                {
                    <div class="mb-3">
                        <label for="idReservacion" class="form-label">ID de la reservacion</label>
                        <input type="text" class="form-control" id="idReservacion" name="idReservacion" required>
                    </div>

                    <div class="mb-3">
                        <label for="idHabitacion" class="form-label">ID de la habitacion</label>
                        <input type="text" class="form-control" id="idHabitacion" name="idHabitacion" required>
                    </div>

                    <div class="mb-3">
                        <label for="fechaReserva" class="form-label">Fecha de la Reserva</label>
                        <input type="text" class="form-control" id="fechaReserva" name="fechaReserva" required>
                    </div>

                    <div class="mb-3">
                        <label for="idReservacion" class="form-label">Reservacion</label>
                        <select class="form-control" id="idReservacion" name="idReservacion">
                            @if (Model.reservaciones.Count > 0)
                            {
                                foreach (var reservacion in Model.reservaciones)
                                {
                                    <option value="@reservacion.idReservacion">@reservacion.idReservacion</option>
                                }
                            }

                        </select>
                    </div>
                    <div class="mb-3">
                        <label for="idHabitacion" class="form-label">Habitacion</label>
                        <select class="form-control" id="idHabitacion" name="idHabitacion">
                            @if (Model.habitaciones.Count > 0)
                            {
                                foreach (var habitacion in Model.habitaciones)
                                {
                                    <option value="@habitacion.idHabitacion">@habitacion.idHabitacion</option>
                                }
                            }

                        </select>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                        <button type="submit" class="btn btn-primary">Guardar</button>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="panel panel-default">
        <table class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>ID del detalle de la reservacion</th>
                    <th>ID de la reservacion</th>
                    <th>ID de la habitacion</th>
                    <th>Fecha de la reserva</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.detalles.Count > 0)

                {
                    foreach (var Detalle in Model.detalles)
                    {
                        <tr>
                            <td>@Detalle.idDetalle</td>
                            <td>@Detalle.idReservacion</td>
                            <td>@Detalle.idHabitacion</td>
                            <td>@Detalle.fechaReserva</td>

                            <td>
                                <button type="button" class="btn btn-primary btn-xs" data-bs-toggle="modal" data-bs-target="#editarModal-@Detalle.idDetalle"><span class="glyphicon glyphicon-edit"></span> Editar</button>
                                <button type="button" class="btn btn-danger btn-xs" data-bs-toggle="modal" data-bs-target="#eliminarModal-@Detalle.idDetalle"><span class="glyphicon glyphicon-remove-circle"></span> Eliminar</button>
                            </td>
                        </tr>



                        <!-- Editar Modal-->
                        <div class="modal fade" id="editarModal-@Detalle.idDetalle" tabindex="-1" aria-labelledby="editarModalLabel" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h1 class="modal-title fs-5" id="editarModalLabel">Editar Empleado</h1>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        @using (Html.BeginForm("Editar", "Detalle", FormMethod.Post))
                                        {
                                            @Html.Hidden("idDetalle", Detalle.idDetalle)
                                            @Html.Hidden("idReservacion", Detalle.idReservacion)
                                            @Html.Hidden("idHabitacion", Detalle.idHabitacion)
                                            <div class="mb-3">
                                                <label for="idDetalle" class="form-label">Id de la reservacion</label>
                                                <input type="text" class="form-control" id="idDetalle" name="idDetalle" value="@Detalle.idDetalle" required readonly>
                                            </div>
                                            <div class="mb-3">
                                                <label for="idReservacion" class="form-label">Id de la reservacion</label>
                                                <input type="text" class="form-control" id="idReservacion" name="idReservacion" value="@Detalle.idReservacion" required readonly>
                                            </div>

                                            <div class="mb-3">
                                                <label for="idHabitacion" class="form-label">Id de la habitacion</label>
                                                <input type="text" class="form-control" id="idHabitacion" name="idHabitacion" value="@Detalle.idHabitacion" required>
                                            </div>

                                            <div class="mb-3">
                                                <label for="fechaReserva" class="form-label">Cargo</label>
                                                <input type="date" class="form-control" id="fechaReserva" name="fechaReserva" value="@Detalle.fechaReserva" required>
                                            </div>

                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                                                <button type="submit" class="btn btn-primary">Guardar</button>
                                            </div>
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>

                        <!-- Eliminar Modal -->
                        <div class="modal fade" id="eliminarModal-@Detalle.idDetalle" tabindex="-1" aria-labelledby="eliminarModalLabel" aria-hidden="true">
                            <div class="modal-dialog modal-dialog-centered">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h1 class="modal-title fs-5" id="eliminarModalLabel">Eliminar Empleado</h1>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        @using (Html.BeginForm("Eliminar", "Detalle", FormMethod.Post))
                                        {
                                            @Html.Hidden("idDetalle", Detalle.idDetalle)
                                            <p>¿Está seguro que desea eliminar al Empleado <strong>@Detalle.idReservacion</strong>?</p>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                                                <button type="submit" class="btn btn-danger">Eliminar</button>
                                            </div>
                                        }
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                }
                else
                {
                    <tr>
                        <td colspan="2" class="text-center">No hay detalles de reservacion registrados.</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>